package cn.juhaowan.cpoywriting.vo;

// Generated 2018-8-23 10:13:29 by Hibernate Tools 3.4.0.CR1

import cn.jugame.dal.annotation.Column;
import cn.jugame.dal.annotation.DbType;
import cn.jugame.dal.annotation.Id;
import cn.jugame.dal.annotation.Table;

/**
 * CopyWriting generated by hbm2java
 */
@Table(name = "copy_writing")
public class CopyWriting implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "id",type = DbType.Int)
	private int id;
	@Column(name = "title", type = DbType.Varchar)
	private String title;
	@Column(name = "content", type = DbType.Varchar)
	private String content;
	@Column(name = "type", type = DbType.Int)
	private int type;
	@Column(name = "platform", type = DbType.Int)
	private int platform;
	@Column(name = "create_time", type = DbType.DateTime)
	private java.util.Date createTime;
	@Column(name = "modify_time", type = DbType.DateTime)
	private java.util.Date modifyTime;
	@Column(name = "status", type = DbType.Int)
	private int status;
	@Column(name = "weight", type = DbType.Int)
	private int weight;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public int getType() {
		return type;
	}
	public void setType(int type) {
		this.type = type;
	}
	public int getPlatform() {
		return platform;
	}
	public void setPlatform(int platform) {
		this.platform = platform;
	}
	public java.util.Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(java.util.Date createTime) {
		this.createTime = createTime;
	}
	public java.util.Date getModifyTime() {
		return modifyTime;
	}
	public void setModifyTime(java.util.Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	public int getWeight() {
		return weight;
	}
	public void setWeight(int weight) {
		this.weight = weight;
	}

}
